# Generated by Django 5.1 on 2024-08-26 14:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
    ]
