# Generated by Django 5.1 on 2024-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0002_alter_site_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
