# Generated by Django 4.2.15 on 2024-10-20 15:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0003_alter_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('configuration', models.CharField(max_length=40, unique=True)),
                ('beds', models.IntegerField()),
                ('storeys', models.IntegerField()),
                ('sales_sq_ft', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('build_sq_ft', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('build_cost', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('build_cost_divide_sq_ft', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('build_Weeks', models.IntegerField()),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('width', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('NDSS', models.BooleanField()),
                ('NDSS_Description', models.CharField(max_length=40, unique=True)),
                ('Accessibility', models.CharField(max_length=40, unique=True)),
                ('parking_spaces', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
            ],
        ),
    ]
