# Generated by Django 4.2.17 on 2024-12-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0004_housetypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housetypes',
            old_name='build_Weeks',
            new_name='build_weeks',
        ),
    ]
