# Generated by Django 4.2.17 on 2024-12-31 18:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0005_rename_build_weeks_housetypes_build_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='housetypes',
            name='plotting_sq_ft',
            field=models.DecimalField(decimal_places=4, default=2342.2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
            preserve_default=False,
        ),
    ]
