# Generated by Django 4.2.17 on 2025-01-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0006_housetypes_plotting_sq_ft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
