# Generated by Django 4.2.17 on 2025-01-11 18:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0007_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='depth',
            field=models.DecimalField(decimal_places=4, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='block',
            name='width',
            field=models.DecimalField(decimal_places=4, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
    ]
