# Generated by Django 4.2.17 on 2025-01-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0008_block_depth_block_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_unit_block',
            field=models.BooleanField(default=True),
        ),
    ]
