# Generated by Django 4.2.17 on 2025-01-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0009_block_is_unit_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='is_unit_block',
        ),
    ]
